import Head from "next/head";
import { useRef, MouseEvent } from "react";
import {
  Box,
  Flex,
  Heading,
  Text,
  IconButton,
  HStack,
  Button,
  VStack,
  Card,
  CardHeader,
  CardBody,
  Grid,
  Progress,
  Divider,
} from "@chakra-ui/react";
import NextImage from "next/image";
import Link from "next/link";

import Header from "../components/Header";
import { AiFillGithub, AiOutlineInstagram } from "react-icons/ai";
import { BsChevronDown } from "react-icons/bs";
import BottomSlideFadeIn from "../components/animations/BottomSlideFadeIn";

export default function Home() {
  const aboutMeRef = useRef<HTMLDivElement>(null);

  const socialMedias = [
    { Icon: AiFillGithub, label: "Github", url: "https://github.com/FranciscoZhou5" },
    { Icon: AiOutlineInstagram, label: "Instagram", url: "https://www.instagram.com/franciscozhou5/" },
  ];

  const profileInfos = [
    { header: "Nome", body: "Francisco Zhou Liu" },
    { header: "Nascimento", body: "12/04/2007" },
    { header: "Cargos", body: "Full-stack developer, Freelancer, Designer" },
    { header: "Email", body: "fg45874587@gmail.com" },
  ];

  function scrollToAboutMeSection() {
    aboutMeRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  return (
    <Box w="full" h="100vh">
      <Head>
        <title>Francisco Zhou Liu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />

      <Box as="section" pos="relative" w="full" textAlign="center" pt="100px" h={{ sm: "550px", md: "600px", lg: "750px" }}>
        <Box mb={{ sm: "16", lg: "80px" }}>
          <BottomSlideFadeIn>
            <Heading size="md" color="primary" mb="2">
              Francisco Zhou
            </Heading>
          </BottomSlideFadeIn>
          <BottomSlideFadeIn>
            <Heading textAlign="center" fontWeight="medium" size={{ sm: "xl", md: "2xl", lg: "4xl" }} mx={{ sm: "0", md: "4" }}>
              Designer & Developer
            </Heading>
          </BottomSlideFadeIn>

          <BottomSlideFadeIn>
            <Text mt={{ sm: "0", md: "4" }} fontSize={{ sm: "medium", md: "large" }} color="#a1a1a1">
              Full-stack developer and UI/UX designer
            </Text>
          </BottomSlideFadeIn>
        </Box>

        <Box>
          <Button
            _hover={{ bgColor: "primary" }}
            borderColor="border"
            variant="outline"
            rightIcon={<BsChevronDown />}
            onClick={scrollToAboutMeSection}
          >
            Saiba mais
          </Button>
        </Box>

        <HStack spacing="4" pos="absolute" bottom="80px" left="50%" transform="translateX(-50%)">
          {socialMedias.map(({ Icon, label, url }) => (
            <Link href={url} target="_blank" key={label}>
              <IconButton aria-label={label} variant="unstyled" _hover={{ color: "primary" }} icon={<Icon size={24} />} />
            </Link>
          ))}
        </HStack>
      </Box>

      <Flex as="section" direction="column" justifyContent="center" alignItems="center" py="16" ref={aboutMeRef} bg="background-secundary">
        <VStack textAlign="center">
          <Heading color="primary" size="md">
            Sobre
          </Heading>
          <Heading> Um pouco sobre o Francisco Zhou... </Heading>
        </VStack>
        <Flex
          direction={{ sm: "column", md: "row" }}
          w="full"
          maxW="580px"
          py="8"
          justifyContent="space-between"
          alignItems={{ sm: "center", md: "start" }}
        >
          <Box position="relative" minW="80px" w="80px" h="80px">
            <NextImage src="/avatar.jpg" alt="Minha foto" fill style={{ borderRadius: "50%" }} />
          </Box>
          <Text
            px={{ sm: "4", md: "0" }}
            color="text-weak"
            m={{ sm: "16px 0", md: "0 0 0 28px" }}
            lineHeight={{ sm: "6", md: "7" }}
            fontSize={{ sm: "15", md: "16" }}
            textAlign={{ sm: "center", md: "unset" }}
          >
            Apaixonado pela área de tecnologia desde criança. Sou atualmente estudante do ensino médio que busca aprender e evoluir para
            oferecer soluções completas para sistemas web, desktop, mobile e servidor.
          </Text>
        </Flex>

        <Grid
          gap="20px"
          templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(2, 1fr)" }}
          px={{ sm: "4", md: "0" }}
          w="full"
          mt={{ sm: "8" }}
          maxW="580px"
          justifyContent="space-between"
        >
          {profileInfos.map((info) => (
            <Flex
              justifyContent="center"
              direction="column"
              key={info.header}
              w="full"
              h="100px"
              p="4"
              bg="background-primary"
              borderRadius="8px"
              border="1px"
              borderColor="border"
              transition="200ms"
              _hover={{ bgColor: "background-secundary" }}
            >
              <Heading size="sm">{info.header}:</Heading>
              <Text mt="4px" color="text-weak" fontSize="15">
                {info.body}
              </Text>
            </Flex>
          ))}
        </Grid>

        <Divider w="20%" my="8" />

        {/* <Flex direction="column" alignItems="center">
          <Heading size="md"> Algumas tecnologias que eu trabalho com... </Heading>
          <HStack mt="4">
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> Typescript </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={86} />
              </Box>
            </Box>
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> React </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={92} />
              </Box>
            </Box>
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> Typescript </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={86} />
              </Box>
            </Box>
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> React </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={92} />
              </Box>
            </Box>
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> Typescript </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={86} />
              </Box>
            </Box>
            <Box bg="background-primary" p="4" borderRadius="8px" minH="180px" minW="350px">
              <Heading size="lg"> React </Heading>
              <Box mt="16">
                <Text> 86% </Text>
                <Progress value={92} />
              </Box>
            </Box>
          </HStack>
        </Flex> */}
      </Flex>

      <Flex as="section" h="500px">
        asdsa
      </Flex>
    </Box>
  );
}
